export enum SortOrder {
  DESCEND = 'desc',
  ASCEND = 'asc',
}

export enum EKiotVietConfig {
  CONNECTION_NAME = 'KIOTVIET_CONNECTION_NAME',
  CLIENT_ID = 'KIOTVIET_CLIENT_ID',
  SECRET_KEY = 'KIOTVIET_SECRET_KEY',
  SHOP_NAME = 'KIOTVIET_SHOP_NAME',
  PASSWORD = 'KIOTVIET_PASSWORD',
  USERNAME = 'KIOTVIET_USERNAME',
  COMMISSION_RATIO = 'RETAILER_COMMISSION_RATIO',
  ACCESS_TOKEN_PUBLIC_API = 'KIOTVIET_ACCESS_TOKEN_PUBLIC_API',
  ACCESS_TOKEN_PRIVATE_API = 'KIOTVIET_ACCESS_TOKEN_PRIVATE_API',
  COOKIE = 'KIOTVIET_COOKIE',
}
