export const TEXT_ONLY = /[0-9]/g;
export const NUMBER_ONLY = /[^0-9]/g;
export const BEGIN_BY_SPACE = /^\s/;
export const INCLUDE_SPACE = /\s/g;
export const MULTIPLE_SPACE_ADJACENT = /\s+/g;
export const VALID_EMAIL_FORMAT = '';
export const MORE_THAN_ONE_EMAIL_SIGN = /^([^@]*@[^@]*)@/;
export const NO_SPECIAL_SYMBOL = /[^a-zA-Z0-9_\-\s]/g;
export const NO_SCRIPT_INJECTION = /[><=^&*]/g;
