/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ABreadcrumb: typeof import('ant-design-vue/es')['Breadcrumb']
    ABreadcrumbItem: typeof import('ant-design-vue/es')['BreadcrumbItem']
    AButton: typeof import('ant-design-vue/es')['Button']
    ACard: typeof import('ant-design-vue/es')['Card']
    ACardMeta: typeof import('ant-design-vue/es')['CardMeta']
    ACheckbox: typeof import('ant-design-vue/es')['Checkbox']
    AConfigProvider: typeof import('ant-design-vue/es')['ConfigProvider']
    AInput: typeof import('ant-design-vue/es')['Input']
    ALayout: typeof import('ant-design-vue/es')['Layout']
    ALayoutContent: typeof import('ant-design-vue/es')['LayoutContent']
    ALayoutFooter: typeof import('ant-design-vue/es')['LayoutFooter']
    ALayoutHeader: typeof import('ant-design-vue/es')['LayoutHeader']
    ALayoutSider: typeof import('ant-design-vue/es')['LayoutSider']
    AMenu: typeof import('ant-design-vue/es')['Menu']
    AMenuItem: typeof import('ant-design-vue/es')['MenuItem']
    ASelect: typeof import('ant-design-vue/es')['Select']
    ASubMenu: typeof import('ant-design-vue/es')['SubMenu']
    CInput: typeof import('./../src/components/core/CInput.vue')['default']
    CustomInput: typeof import('./../src/components/common/CustomInput.vue')['default']
    HelloComp: typeof import('./../src/components/HelloComp.vue')['default']
    NewCompTwo: typeof import('./../src/components/NewCompTwo.vue')['default']
    ProductCardInfo: typeof import('./../src/components/ecom/ProductCardInfo.vue')['default']
    QuantityItemControl: typeof import('./../src/components/common/QuantityItemControl.vue')['default']
    QuantityNumberControl: typeof import('./../src/components/ecom/QuantityNumberControl.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UnitConverionOptions: typeof import('./../src/components/common/UnitConverionOptions.vue')['default']
  }
}
